
package com.midea.cloud.srm.supcooperate.soap.erp.service;

import com.midea.cloud.srm.model.suppliercooperate.soap.erp.invoice.OnlineInvoiceInputParameters;
import com.midea.cloud.srm.model.suppliercooperate.soap.erp.invoice.OnlineInvoiceObjectFactory;
import com.midea.cloud.srm.model.suppliercooperate.soap.erp.invoice.OnlineInvoiceOutputParameters;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ErpAcceptPoRcvRtnLockSoapBiz_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/LongiServiceBusApp/SRMSB/ErpAcceptPoRcvRtnLockSoapBiz")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    OnlineInvoiceObjectFactory.class
})
public interface ErpAcceptPoRcvRtnLockSoapBizPtt {


    /**
     * 
     * @param inputParameters
     * @return
     *     returns com.oracle.xmlns.pcbpel.adapter.db.sp.erpacceptporcvrtnlocksoapbiz.OutputParameters
     */
    @WebMethod(operationName = "ErpAcceptPoRcvRtnLockSoapBiz", action = "ErpAcceptPoRcvRtnLockSoapBiz")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/ErpAcceptPoRcvRtnLockSoapBiz", partName = "OutputParameters")
    public OnlineInvoiceOutputParameters erpAcceptPoRcvRtnLockSoapBiz(
            @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/ErpAcceptPoRcvRtnLockSoapBiz", partName = "InputParameters")
                    OnlineInvoiceInputParameters inputParameters);

}
