
package com.midea.cloud.srm.cm.accept.soap.assetsreimbursement;

import com.midea.cloud.srm.cm.CmSaopUrl;
import org.springframework.beans.factory.annotation.Value;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.PostConstruct;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "receivableTypeInfoService", targetNamespace = "http://soap.f10.vispractice.com"
     //   , wsdlLocation = "http://10.0.10.26/fssc-eas-web/apis/ws/fssc/eas/thirdws/BusinessFormInfoServiceImpl?wsdl"
)
public class ReceivableTypeInfoService
    extends Service
{
    private final static URL RECEIVABLETYPEINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECEIVABLETYPEINFOSERVICE_EXCEPTION;
    private final static QName RECEIVABLETYPEINFOSERVICE_QNAME = new QName("http://soap.f10.vispractice.com", "receivableTypeInfoService");

    static {

        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(CmSaopUrl.acceptOrderUrl);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVABLETYPEINFOSERVICE_WSDL_LOCATION = url;
        RECEIVABLETYPEINFOSERVICE_EXCEPTION = e;
    }

    public ReceivableTypeInfoService() {
        super(__getWsdlLocation(), RECEIVABLETYPEINFOSERVICE_QNAME);
    }

    public ReceivableTypeInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVABLETYPEINFOSERVICE_QNAME, features);
    }

    public ReceivableTypeInfoService(URL wsdlLocation) {
        super(wsdlLocation, RECEIVABLETYPEINFOSERVICE_QNAME);
    }

    public ReceivableTypeInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVABLETYPEINFOSERVICE_QNAME, features);
    }

    public ReceivableTypeInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceivableTypeInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BusinessFormInfoService
     */
    @WebEndpoint(name = "BusinessFormInfoServiceImplPort")
    public BusinessFormInfoService getBusinessFormInfoServiceImplPort() {
        return super.getPort(new QName("http://soap.f10.vispractice.com", "BusinessFormInfoServiceImplPort"), BusinessFormInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessFormInfoService
     */
    @WebEndpoint(name = "BusinessFormInfoServiceImplPort")
    public BusinessFormInfoService getBusinessFormInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.f10.vispractice.com", "BusinessFormInfoServiceImplPort"), BusinessFormInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVABLETYPEINFOSERVICE_EXCEPTION!= null) {
            throw RECEIVABLETYPEINFOSERVICE_EXCEPTION;
        }
        return RECEIVABLETYPEINFOSERVICE_WSDL_LOCATION;
    }

}
