
package com.midea.cloud.srm.supcooperate.deliverynote.soap.erpacceptvendorshipmentsoapbiz;

import com.midea.cloud.srm.model.suppliercooperate.deliverynote.soap.erpacceptvendorshipmentsoapbiz.AcceptVendorFactory;
import com.midea.cloud.srm.model.suppliercooperate.deliverynote.soap.erpacceptvendorshipmentsoapbiz.InputAcceptVendor;
import com.midea.cloud.srm.model.suppliercooperate.deliverynote.soap.erpacceptvendorshipmentsoapbiz.OutputAcceptVendor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ErpAcceptVendorShipmentSoapBiz_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/NSrm/ErpAcceptVendorShipmentSoapBiz")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        AcceptVendorFactory.class
})
public interface ErpAcceptVendorShipmentSoapBizPtt {


    /**
     * @param inputParameters
     * @return returns com.oracle.xmlns.pcbpel.adapter.db.sp.erpacceptvendorshipmentsoapbiz.OutputParameters
     */
    @WebMethod(operationName = "ErpAcceptVendorShipmentSoapBiz", action = "ErpAcceptVendorShipmentSoapBiz")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/ErpAcceptVendorShipmentSoapBiz", partName = "OutputParameters")
    public OutputAcceptVendor erpAcceptVendorShipmentSoapBiz(
            @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/ErpAcceptVendorShipmentSoapBiz", partName = "InputParameters")
                    InputAcceptVendor inputParameters);

}
