
package com.midea.cloud.srm.po.order.soap.service;

import com.midea.cloud.srm.model.pm.soap.order.APPSCUXPOORDERSMOX1362358X4X7;
import com.midea.cloud.srm.model.pm.soap.order.OrderChangeInputParameters;
import com.midea.cloud.srm.po.PoSoapUrl;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ErpCancelPurchaseOrderSoapBiz_ptt-bindingQSService", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/NSrm/ErpCancelPurchaseOrderSoapBiz"
//        , wsdlLocation = "http://soatest.longi.com:8011/NSrm/Erp/PurchaseOrder/ProxyServices/ErpCancelPurchaseOrderSoapProxy?wsdl"
)
public class ErpCancelPurchaseOrderSoapBizPttBindingQSService
        extends Service
{

    private final static URL ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_EXCEPTION;
    private final static QName ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_QNAME = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/NSrm/ErpCancelPurchaseOrderSoapBiz", "ErpCancelPurchaseOrderSoapBiz_ptt-bindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PoSoapUrl.urlEditPurchaseOrder);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_WSDL_LOCATION = url;
        ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public ErpCancelPurchaseOrderSoapBizPttBindingQSService() {
        super(__getWsdlLocation(), ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_QNAME);
    }

    public ErpCancelPurchaseOrderSoapBizPttBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_QNAME, features);
    }

    public ErpCancelPurchaseOrderSoapBizPttBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_QNAME);
    }

    public ErpCancelPurchaseOrderSoapBizPttBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_QNAME, features);
    }

    public ErpCancelPurchaseOrderSoapBizPttBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErpCancelPurchaseOrderSoapBizPttBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ErpCancelPurchaseOrderSoapBizPtt
     */
    @WebEndpoint(name = "ErpCancelPurchaseOrderSoapBiz_ptt-bindingQSPort")
    public ErpCancelPurchaseOrderSoapBizPtt getErpCancelPurchaseOrderSoapBizPttBindingQSPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/NSrm/ErpCancelPurchaseOrderSoapBiz", "ErpCancelPurchaseOrderSoapBiz_ptt-bindingQSPort"), ErpCancelPurchaseOrderSoapBizPtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErpCancelPurchaseOrderSoapBizPtt
     */
    @WebEndpoint(name = "ErpCancelPurchaseOrderSoapBiz_ptt-bindingQSPort")
    public ErpCancelPurchaseOrderSoapBizPtt getErpCancelPurchaseOrderSoapBizPttBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/NSrm/ErpCancelPurchaseOrderSoapBiz", "ErpCancelPurchaseOrderSoapBiz_ptt-bindingQSPort"), ErpCancelPurchaseOrderSoapBizPtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_EXCEPTION;
        }
        return ERPCANCELPURCHASEORDERSOAPBIZPTTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
