
/*
 *
 */

package com.midea.cloud.srm.po.logisticsOrder.soap.service.impl;

import com.midea.cloud.srm.po.logisticsOrder.soap.service.LogisticsContractRatePtt;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Jan 19 11:39:56 CST 2021
 * Generated source version: 2.2.4
 *
 */


@WebServiceClient(name = "LogisticsContractRate_bindQSService",
                  wsdlLocation = "http://soatest.longi.com:8011/TMSSB/Srm/LogisticsContractRate/ProxyServices/TmsAcceptLogisticsContractRateSoapProxy?wsdl",
                  targetNamespace = "http://www.longi.com/TMSSB/Srm/LogisticsContractRate/WSDLs/v1.0")
public class LogisticsContractRateBindQSService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.longi.com/TMSSB/Srm/LogisticsContractRate/WSDLs/v1.0", "LogisticsContractRate_bindQSService");
    public final static QName LogisticsContractRateBindQSPort = new QName("http://www.longi.com/TMSSB/Srm/LogisticsContractRate/WSDLs/v1.0", "LogisticsContractRate_bindQSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://soatest.longi.com:8011/TMSSB/Srm/LogisticsContractRate/ProxyServices/TmsAcceptLogisticsContractRateSoapProxy?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://soatest.longi.com:8011/TMSSB/Srm/LogisticsContractRate/ProxyServices/TmsAcceptLogisticsContractRateSoapProxy?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public LogisticsContractRateBindQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LogisticsContractRateBindQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogisticsContractRateBindQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns LogisticsContractRatePtt
     */
    @WebEndpoint(name = "LogisticsContractRate_bindQSPort")
    public LogisticsContractRatePtt getLogisticsContractRateBindQSPort() {
        return super.getPort(LogisticsContractRateBindQSPort, LogisticsContractRatePtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogisticsContractRatePtt
     */
    @WebEndpoint(name = "LogisticsContractRate_bindQSPort")
    public LogisticsContractRatePtt getLogisticsContractRateBindQSPort(WebServiceFeature... features) {
        return super.getPort(LogisticsContractRateBindQSPort, LogisticsContractRatePtt.class, features);
    }

}
