
package com.midea.cloud.srm.po.logisticsOrder.soap.service.impl;

import com.midea.cloud.srm.po.logisticsOrder.soap.service.ITmsLogisticsOrderWsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "TmsLogisticsOrderWsServiceImplService", targetNamespace = "http://www.aurora-framework.org/schema", wsdlLocation = "http://localhost:8842/registerService/TmsLogisticsOrderWsServiceImpl?wsdl")
public class TmsLogisticsOrderWsServiceImplService
    extends Service
{

    private final static URL TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_QNAME = new QName("http://www.aurora-framework.org/schema", "TmsLogisticsOrderWsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8842/registerService/TmsLogisticsOrderWsServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TmsLogisticsOrderWsServiceImplService() {
        super(__getWsdlLocation(), TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_QNAME);
    }

    public TmsLogisticsOrderWsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TmsLogisticsOrderWsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_QNAME);
    }

    public TmsLogisticsOrderWsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TmsLogisticsOrderWsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TmsLogisticsOrderWsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ITmsLogisticsOrderWsService
     */
    @WebEndpoint(name = "TmsLogisticsOrderWsServiceImplPort")
    public ITmsLogisticsOrderWsService getTmsLogisticsOrderWsServiceImplPort() {
        return super.getPort(new QName("http://www.aurora-framework.org/schema", "TmsLogisticsOrderWsServiceImplPort"), ITmsLogisticsOrderWsService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITmsLogisticsOrderWsService
     */
    @WebEndpoint(name = "TmsLogisticsOrderWsServiceImplPort")
    public ITmsLogisticsOrderWsService getTmsLogisticsOrderWsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aurora-framework.org/schema", "TmsLogisticsOrderWsServiceImplPort"), ITmsLogisticsOrderWsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TMSLOGISTICSORDERWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
